from time import sleep
import common
import autoFindRoad

def start():
    common.otherKeys('a')
    sleep(0.2)
    common.otherKeys('s')
    sleep(0.2)
    autoFindRoad.findDoorPlus(100)
    sleep(0.5)
    common.run(0.7)
    common.otherKeys('w')
    sleep(0.5)
    common.run(0.2)

    autoFindRoad.findDoorPlus(100)
    sleep(0.5)
    autoFindRoad.moveRoleToYCenter()
    common.run(0.4)
    common.otherKeys('r')
    sleep(1)
    common.otherKeys('q')
    sleep(0.3)
    common.run(0.2)

    autoFindRoad.findDoorPlus(100)
    sleep(0.5)
    autoFindRoad.moveRoleToYCenter()
    common.run(0.7)
    common.otherKeys('g')
    sleep(1)
    common.run(0.2)

    autoFindRoad.findDoorPlus(100)
    sleep(0.5)
    autoFindRoad.moveRoleToYCenter()
    common.run(0.5)
    common.otherKeys('y')
    sleep(1.5)
    common.run(0.2)
    common.otherKeys('q')
    sleep(0.3)

    autoFindRoad.findDoorPlus(100)
    common.run(0.2)
    autoFindRoad.moveRoleToYCenter()
    common.otherKeys('t')
    sleep(0.8)
    common.otherKeys('alt')
    sleep(3)