from time import sleep
import common
import autoFindRoad

def start():

    common.otherKeys('y')
    sleep(0.5)
    autoFindRoad.findDoorPlus(100)
    sleep(0.5)
    autoFindRoad.moveRoleToYCenter()
    common.otherKeys('a')
    sleep(0.5)
    common.run(0.1)
    common.otherKeys('w')
    sleep(0.5)
    common.run(0.3)

    autoFindRoad.findDoorPlus(100)
    sleep(0.5)
    common.otherKeys('a')
    sleep(0.5)
    common.otherKeys('f')
    sleep(1.5)
    common.run(0.6)

    autoFindRoad.findDoorPlus(100)
    sleep(0.5)
    autoFindRoad.moveRoleToYCenter()
    common.otherKeys('a')
    sleep(0.5)
    common.run(0.2)
    common.otherKeys('d')
    sleep(0.5)
    common.run(0.2)

    autoFindRoad.findDoorPlus(100)
    sleep(0.5)
    autoFindRoad.moveRoleToYCenter()
    common.otherKeys('a')
    sleep(0.3)
    common.run(0.2)
    common.otherKeys('g')
    sleep(0.5)
    common.run(0.1)

    autoFindRoad.findDoorPlus(100)
    autoFindRoad.moveRoleToYCenter()
    common.run(0.2)
    common.otherKeys('a')
    sleep(0.1)
    common.otherKeys('w')
    sleep(0.3)
    common.otherKeys('r')
    sleep(0.5)
    common.otherKeys('e')
    sleep(4)