from time import sleep
import common
import autoFindRoad


def start():
    common.otherKeys('y')
    sleep(0.5)
    common.otherKeys('ctrl')
    sleep(0.5)
    common.otherKeys('g')
    sleep(1)
    autoFindRoad.findDoorPlus(100)
    sleep(0.5)
    common.run(0.3)
    common.otherKeys('s')
    sleep(0.5)
    common.run(0.2)
    common.otherKeys('e')
    sleep(0.5)
    common.run(0.4)

    autoFindRoad.findDoorPlus(100)
    sleep(0.8)
    autoFindRoad.moveRoleToYCenter()
    common.run(0.3)
    common.otherKeys('d')
    common.run(0.7)

    autoFindRoad.findDoorPlus(100)
    sleep(0.5)
    autoFindRoad.moveRoleToYCenter()
    common.run(0.4)
    common.otherKeys('t')
    sleep(1)
    common.otherKeys('w')
    sleep(0.5)
    common.run(0.7)

    autoFindRoad.findDoorPlus(100)
    sleep(0.5)
    autoFindRoad.moveRoleToYCenter()
    common.run(0.3)
    common.otherKeys('f')
    common.run(0.5)

    autoFindRoad.findDoorPlus(100)
    common.run(0.4)
    autoFindRoad.moveRoleToYCenter()
    common.otherKeys('s')
    sleep(0.5)
    common.otherKeys('alt')
    sleep(2)
    common.otherKeys('a')
    sleep(3)
