from cmath import e
from time import sleep
import common
import normal
import autoFindRoad
import auto


def start():
    while True:
        if autoFindRoad.checkFatigueValueisClear() is True:
            common.otherKeys('f12')
            sleep(5)
            autoFindRoad.sealGoogsAndFix()
            break
        common.otherKeys('y')
        autoFindRoad.findDoorPlus(78)
        common.moveFunc('top', 1.25)
        common.moveFunc('right', 0.2)
        common.otherKeys('q')
        sleep(2)
        while (auto.judgeMap('1') or auto.judgeMap('6')) is False:
            common.moveFunc('right', 0.3)
            common.otherKeys('w')
            sleep(0.5)
            common.otherKeys('e')
            sleep(5)
            common.moveFunc('left', 0.2)
            common.otherKeys('w')
            sleep(0.5)
            common.otherKeys('a')
        autoFindRoad.findDoorPlus(78, True)
        if auto.checkHasEpic() is True:
            common.moveFunc('right', 0.7)
            normal.changePickEpic()
            common.moveFunc('left', 0.7)
        sleep(0.8)
        common.run(0.2, 'left')
        normal.moveRoleToYCenter(80)
        common.otherKeys('f')
        common.run(0.4, 'left')
        sleep(1)
        # common.moveFunc('bottom', 0.5)
        # common.otherKeys('w')
        # sleep(0.5)
        # common.otherKeys('r')
        # sleep(1)
        while (auto.judgeMap('2') or auto.judgeMap('7')) is False:
            common.moveFunc('right', 0.3)
            common.otherKeys('w')
            sleep(0.5)
            common.otherKeys('e')
            sleep(5)
            common.moveFunc('left', 0.2)
            common.otherKeys('w')
            sleep(0.5)
            common.otherKeys('a')
        autoFindRoad.findDoorPlus(78, True)
        if auto.checkHasEpic() is True:
            common.moveFunc('bottom', 0.3)
            normal.changePickEpic()
            common.moveFunc('top', 0.3)
        common.moveFunc('top', 1.35)
        common.run(0.14)
        common.otherKeys('s')
        common.otherKeys('d')
        sleep(0.5)
        common.moveFunc('top', 0.4)
        sleep(3)
        common.moveFunc('bottom', 0.3)
        common.run(0.75)
        while (auto.judgeMap('3') or auto.judgeMap('8')) is False:
            common.moveFunc('right', 0.3)
            common.otherKeys('w')
            sleep(0.5)
            common.otherKeys('e')
            sleep(5)
            common.moveFunc('left', 0.2)
            common.otherKeys('w')
            sleep(0.5)
            common.otherKeys('a')
        autoFindRoad.findDoorPlus(78)
        if auto.checkHasEpic() is True:
            common.moveFunc('left', 0.4)
            normal.changePickEpic()
            common.moveFunc('right', 0.4)
        common.moveFunc('right', 0.3)
        normal.moveRoleToYCenter(85, [0,0,400,600])
        common.otherKeys('w')
        sleep(0.8)
        common.otherKeys('a')
        sleep(0.5)
        common.otherKeys('q')
        sleep(1)
        common.moveFunc('bottom', 0.3)
        while (auto.judgeMap('4') or auto.judgeMap('9')) is False:
            common.moveFunc('right', 0.3)
            common.otherKeys('e')
            common.moveFunc('left', 0.2)
            common.otherKeys('a')
        autoFindRoad.findDoorPlus(78, False, True)
        if auto.checkHasEpic() is True:
            common.moveFunc('bottom', 0.4)
            normal.changePickEpic()
            common.moveFunc('top', 0.4)
        sleep(0.5)
        common.moveFunc('top', 1)
        common.moveFunc('right', 0.01)
        common.otherKeys('g')
        sleep(6)
        taskx, taskYy = auto.checkHasTask()
        if taskx != 0:
            common.run(1, 'left')
            common.moveFunc('bottom', 1)
            common.run(4)
            common.moveFunc('left', 0.8)
            autoFindRoad.findDoorPlus(78)
            common.moveFunc('top', 0.5)
            sleep(3)
        else:
            common.run(0.8)
            while (auto.judgeMap('5') or auto.judgeMap('10')) is False:
                common.moveFunc('right', 0.3)
                common.otherKeys('w')
                sleep(0.5)
                common.otherKeys('e')
                sleep(5)
                common.moveFunc('left', 0.2)
                common.otherKeys('w')
                sleep(0.5)
                common.otherKeys('a')
            autoFindRoad.findDoorPlus(78)
            if auto.checkHasEpic() is True:
                common.moveFunc('bottom', 0.4)
                normal.changePickEpic()
                common.moveFunc('top', 0.4)
        common.moveFunc('top', 0.7)
        common.run(0.35, 'left')
        common.otherKeys('f')
        sleep(4.5)
        common.otherKeys('`')
        sleep(3)
        common.otherKeys('x')
        common.otherKeys('x')
        common.otherKeys('x')
        common.otherKeys('x')
        common.otherKeys('esc')
        sleep(3)
        common.otherKeys('esc')
        sleep(5)
        common.otherKeys('R_ctrl')
        sleep(5)
start()
