from time import sleep
import common
import auto
import autoFindRoad

def start():
    autoFindRoad.findDoorPlus(61)
    common.moveFunc('top', 1)
    common.run(0.5)
    common.otherKeys('a')
    sleep(1)
    common.otherKeys('g')
    sleep(3)
    # 判断第二个地图是否清完野怪，如果没有清理完，需要重复走动并释放大范围技能进行清除
    while auto.judgeMap('1') is False:
        common.otherKeys('t')
        sleep(1)
        common.run(4)
        common.otherKeys('f')
        sleep(5)
        common.run(2, 'left')
        common.otherKeys('w')
        sleep(18)
    autoFindRoad.findDoorPlus(61, True)
    sleep(2)
    # 判断是否成功进入下一个地图，（可能上一次自动寻路出现问题，导致寻路失败，需要重新自动寻路）
    while auto.judgeMap('2', True) is False:
        common.run(2)
        autoFindRoad.findDoorPlus(61, True)
        sleep(2)
    common.run(0.1, 'left')
    common.otherKeys('d')
    sleep(1)
    common.moveFunc('bottom', 0.5)
    common.otherKeys('q')
    sleep(3)
    common.run(0.5, 'left')
    # 判断第三个地图是否清完野怪，如果没有清理完，需要重复走动并释放大范围技能进行清除
    while auto.judgeMap('2') is False:
        common.otherKeys('t')
        sleep(1)
        common.run(1)
        common.otherKeys('f')
        sleep(5)
        common.run(1.5, 'left')
        common.otherKeys('w')
        sleep(18)
    autoFindRoad.findDoorPlus(61, True)
    sleep(2)
    while auto.judgeMap('3', True) is False:
        common.run(1.5)
        autoFindRoad.findDoorPlus(61, True)
        sleep(2)
    common.moveFunc('top', 1)
    common.run(0.2)
    common.otherKeys('alt')
    common.run(0.5)
    sleep(3)
    # 判断第四个地图是否清完野怪，如果没有清理完，需要重复走动并释放大范围技能进行清除
    while auto.judgeMap('3') is False:
        common.otherKeys('t')
        sleep(1)
        common.run(1)
        common.otherKeys('f')
        sleep(5)
        common.run(1.5, 'left')
        common.otherKeys('w')
        sleep(18)
    autoFindRoad.findDoorPlus(61)
    sleep(2)
    while auto.judgeMap('4', True) is False:
        common.run(1.5, 'left')
        autoFindRoad.findDoorPlus(61)
        sleep(2)
    common.run(0.6)
    common.otherKeys('e')
    sleep(1)
    common.moveFunc('right', 0.3)
    common.otherKeys('a')
    sleep(2)
    common.otherKeys('r')
    sleep(3)
    common.moveFunc('bottom', 1)
    # 判断第五个地图是否清完野怪，如果没有清理完，需要重复走动并释放大范围技能进行清除
    while auto.judgeMap('4') is False:
        common.otherKeys('t')
        sleep(1)
        common.run(1)
        common.otherKeys('f')
        sleep(5)
        common.run(1.5, 'left')
        common.otherKeys('w')
        sleep(18)
    autoFindRoad.findDoorPlus(61, False, True)
    sleep(2)
    while auto.judgeMap('5', True) is False:
        common.run(1.5, 'left')
        autoFindRoad.findDoorPlus(61, False, True)
        sleep(2)
    common.moveFunc('top', 1)
    common.moveFunc('right', 0.01)
    common.otherKeys('d')
    sleep(1)
    common.moveFunc('left', 0.01)
    common.otherKeys('q')
    sleep(1)
    common.otherKeys('g')
    sleep(3)
    common.run(1)
    # 判断第六个地图是否清完野怪，如果没有清理完，需要重复走动并释放大范围技能进行清除
    while auto.judgeMap('5') is False:
        common.otherKeys('t')
        sleep(1)
        common.run(1.5)
        common.otherKeys('f')
        sleep(5)
        common.run(1, 'left')
        common.otherKeys('w')
        sleep(18)
    autoFindRoad.findDoorPlus(61)
    sleep(2)
    while auto.judgeMap('6', True) is False:
        common.run(1.5, 'left')
        autoFindRoad.findDoorPlus(61)
        sleep(2)
    common.otherKeys('h')
    sleep(0.5)
    common.moveFunc('top', 1)
    common.moveFunc('left', 0.3)
    common.otherKeys('alt')
    sleep(1)
    common.otherKeys('ctrl')
    sleep(4)
    common.otherKeys('r')
    sleep(1)
    common.otherKeys('w')
    sleep(1)
    common.otherKeys('y')
start()